#ifndef ERROR_LIST_S_R_H
#define ERROR_LIST_S_R_H

enum SRError{
  SR_ERROR_OK,
  SR_ERROR_IMAGE_PAIR_NOT_EXIST_ERROR,
  SR_ERROR_CAMERA_PAIR_PARAMS_NOT_EXIST_ERROR,
  SR_ERROR_ZERO_DISPARITY_ERROR,
  SR_ERROR_DIVISION_BY_ZERO_ERROR,
  SR_ERROR_INPUT_POINT_CLOUD_IS_EMPTY_ERROR,
	SR_ERROR_INPUT_IMAGES_IS_EMPTY_ERROR,
  SR_ERROR_INPUT_TRANSITION_MAT_IS_EMPTY_ERROR,
  SR_ERROR_WRONG_INPUT_MAT_SIZE_ERROR,
  SR_ERROR_WRONG_MAT_SIZE_ERROR,
  SR_ERROR_UNFOUND_CONTROL_AREA_CENTER_ERROR,
	SR_ERROR_WRONG_INPUT_PARAMS_ERROR
};

#endif